[font]
#default is 11.25
size = 11.75

[font.bold]
#family = "FiraCode Nerd Font"
#family = "JetBrainsMono Nerd Font"
family = "Cascadia Code NF"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[window]
decorations = "None"

[window.padding]
x = 5
y = 0
