[font]
# default is 11.25
#size = 11.75
size = 11.50

[font.normal]
#family = "FiraCode Nerd Font"
#family = "Cascadia Code NF"
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
decorations = "None"

[window.padding]
x = 5
y = 0
