#import = ["/home/phoenix/.config/alacritty/alacritty_everforest.toml"]
import = ["~/.config/alacritty/cyberdream.toml"]

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 0
