[font]
size = 12.0

[font.bold]
#family = "FiraCode Nerd Font"
#family = "JetBrainsMono Nerd Font"
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window]
decorations = "None"

[window.padding]
x = 5
y = 0
