#import = ["/home/phoenix/.config/alacritty/alacritty_everforest.toml"]
#import = ["/home/phoenix/.config/alacritty/alacritty_kanagawa.yml"]
import = ["/home/phoenix/.config/alacritty/alacritty_iceberg.yml"]

[font]
size = 13.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 0
